name = input('What is your name? ')
print('Hi ' + name)
color = input('What is your favorite color? ')
print('Your favorite color is ' + color)
food = input('What is your favorite food? ')
print('Your favorite food is ' + food)
game = input('What is your favorite game? ')
print('Your favorite game is ' + game)
sexual_activity = input('What is your favorite sexual activity? ')
print('Your favorite sexual activity is ' + sexual_activity)
big_ass_or_big_tits = input('Do you like big ass or big tits? ')
print('You like ' + big_ass_or_big_tits)
aliens = input('Do you believe in aliens? ')
print('Yes ' + aliens)
alcoholic_drink = input('What is your favorite alcoholic drink? ')
print('Your favorite alcoholic drink is ' + alcoholic_drink)
mass_effect = input('Tell me more about mass effect ')
print('Mass effect is ' + mass_effect)
elon_musk = input('What do you think of elon musk? ')
print('Elon musk is ' + elon_musk)
stock_market = input('What do you know about the stock market? ')
print('You know that the ' + stock_market)
crypto = input('What do you know about crypto? ')
print('You know that ' + crypto)
intel = input('What do you know about intel corporation? ')
print('I know that ' + intel)
amd = input('What do you know about amd corporation? ')
print('I know that ' + amd)
climate_change = input('Do you believe humanity can combat climate change effectively? ')
print('Yes i do because ' + climate_change)
humanity = input('What are your opinions about the future of humanity? ')
print('I strongly believe that ' + humanity)
mars = input('Is elon musk right about mars? ')
print('Yes but ' + mars)
business = input('What is your preferred business model? ')
print('Your preferred business model is ' + business)
twitter = input('What do you know about twitter? ')
print('You know that ' + twitter)
water = input('What do you know about water? ')
print('I understand that ' + water)
weed = input('What do you know about the common and diverse herb known as weed? ')
print('I know that ' + weed)
gaming = input('Why do you like gaming? ')
print('I like gaming because ' + gaming)
art = input('What can you tell me about art? ')
print('I know very well that ' + art)
american_culture = input('What can you tell me about about american culture? ')
print('American culture is ' + american_culture)
wild_west = input('Are you interested in the wild west and why? ')
print('Yes i do because ' + wild_west)
gym_exercise = input('Whats you favorite gym exercise? ')
print('My favorite gym exercise is ' + gym_exercise)
ps5 = input('whats your favorite ps5 game? ')
print('My favorite ps5 game is ' + ps5)
family = input('Do you love your family? ')
print('Yes ' + family)
hangout_spot = input('Whats your preferred hangout spot? ')
print('My preferred hangout spot is ' + hangout_spot)
shoe_brand = input('Whats your preferred shoe brand? ')
print('My preferred shoe brand is ' + shoe_brand)
division_2 = input('Do you enjoy playing division 2 and why? ')
print('Yes i do and i enjoy playing division 2 because ' + division_2)
game_of_thrones = input('Whats your favorite game of thrones character? ')
print('My favorite game of thrones character is ' + game_of_thrones)
nigeria = input('What year did nigeria gain her independence? ')
print('Nigeria gained her independence in ' + nigeria)
nigeria_states = input('How many states are currently in nigeria? ')
print('Nigeria has ' + nigeria_states)
universal_language = input('Whats the worlds universal language? ')
print('The worlds universal language is ' + universal_language)
dying_light_2 = input('What month and year was dying light 2 released? ')
print('Dying light 2 was released on ' + dying_light_2)
dying_light_2_mc = input('Who is the main character in dying light 2? ')
print('The main character of dying light 2 is ' + dying_light_2_mc)
fps_game = input('What game revolutionized the fps genre? ')
print('The game is ' + fps_game)
usa_president = input('Who is the current president of america? ')
print('The current president of america is ' + usa_president)
ceo_apple = input('Who is the current ceo of apple? ')
print('The current ceo of apple is ' + ceo_apple)
iphone = input('What iphone model is releasing this september 2022? ')
print('The iphone model releasing this month is ' + iphone)
nigeria_currency = input('Whats nigeria main currency? ')
print('Nigeria main currency is ' + nigeria_currency)
british_currency = input('Whats the british main currency? ')
print('The british main currency is ' + british_currency)
cyberpunk_2077 = input('Do you like cyberpunk 2077 and why? ')
print('Yes i do because ' + cyberpunk_2077)
automotive_company_ai = input('What automotive company is leading the world in AI powered vehicles? ')
print('The automotive company leading the world in AI powered vehicles is ' + automotive_company_ai)
automotive_ai_company = input('Whats the name of this automotive AI company? ')
print('The name of this automotive AI company is ' + automotive_ai_company)
richest_man = input('Who is the current richest man in the world? ')
print('The worlds current richest man is ' + richest_man)
gta_san_andreas = input('What is the name of the main character in gta san andreas? ')
print('The main character in gta san andreas is ' + gta_san_andreas)
artificial_intelligence = input('What do you think about artificial intelligence? ')
print('Artificial intelligence is ' + artificial_intelligence)
america_currency = input('Whats americas main currency? ')
print('Americas main currency is ' + america_currency)